version: '3.9'


services:
  api:
    image: hexars:0.1.1
    container_name: hexars_api
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env.prod
    ports:
      - 3000:3000
    extra_hosts:
      - "host.docker.internal:host-gateway"
